name: Generated APK AAB (Upload - Create Artifact To Github Action)

on:

  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-go@v5
        with:
            go-version: '>=1.21.0'

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
            cmake-version: '3.16.x'

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Create APK Release
      - name: Build apk release project (APK)
        run: ./gradlew assembleRelease
